yarnPath: ".yarn/releases/yarn-2.4.1.cjs"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
    
nodeLinker: node-modules
nmHoistingLimits: "workspaces"

logFilters:
  # Consider incorrect dependencies as errors instead of warnings
  - code: YN0002
    level: error
  # Consider incorrect versions of peerDependencies as warnings
  # Hopefully, we will be able to change this, but there are
  # no way for us to fix those warnings.
  - code: YN0060
    level: "warning"

packageExtensions:
  "@buffetjs/core@*":
    peerDependencies:
      "@babel/runtime": "*"
  "@buffetjs/custom@*":
    peerDependencies:
      "@babel/runtime": "*"
      react-dom: "*"
  "@buffetjs/styles@*":
    peerDependencies:
      "@babel/runtime": "*"
      moment: "*"
      react-dom: "*"
  "@chakra-ui/accordion@1.3.1":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@1.1.12":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@1.2.5":
    peerDependencies:
      framer-motion: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: "*"
  "@graphql-codegen/cli@1.21.4":
    peerDependencies:
      typescript: "*"
  "@storybook/core@*":
    peerDependencies:
      webpack: "*"
  eslint-config-airbnb-typescript@12.3.1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  graphql-config@3.3.0:
    peerDependencies:
      typescript: "*"
  next-pwa@*:
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  realistic-structured-clone@2.0.2:
    dependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  strapi-admin@*:
    peerDependencies:
      jquery: "*"
      popper.js: "*"
  strapi-helper-plugin@*:
    peerDependencies:
      "@babel/runtime": "*"
      jquery: "*"
      popper.js: "*"
      react-is: "*"
  strapi-plugin-content-manager@*:
    peerDependencies:
      "@babel/runtime": "*"
      jquery: "*"
      moment: "*"
      popper.js: "*"
      react-is: "*"
      styled-components: "*"
  strapi-plugin-content-type-builder@*:
    peerDependencies:
      "@babel/runtime": "*"
      jquery: "*"
      moment: "*"
      popper.js: "*"
      react-is: "*"
      styled-components: "*"
  strapi-plugin-graphql@*:
    peerDependencies:
      koa: "*"
  strapi-plugin-upload@*:
    peerDependencies:
      "@babel/runtime": "*"
      jquery: "*"
      moment: "*"
      popper.js: "*"
      react-is: "*"
      redux: "*"
      styled-components: "*"
  strapi-plugin-users-permissions@*:
    peerDependencies:
      "@babel/runtime": "*"
      jquery: "*"
      koa: "*"
      moment: "*"
      popper.js: "*"
      react-is: "*"
      redux: "*"
      styled-components: "*"


      