logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: warning

nodeLinker: node-modules

packageExtensions:
  "@chakra-ui/accordion@1.3.6":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/anatomy@1.0.0":
    peerDependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/skeleton@1.1.18":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@1.2.9":
    peerDependencies:
      framer-motion: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: "*"
  "@graphql-codegen/cli@1.21.4":
    peerDependencies:
      typescript: "*"
  "@storybook/core-server@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/store@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/csf-tools@*":
    peerDependencies:
      "@babel/core": "*"
  eslint-config-airbnb-typescript@12.3.1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  graphql-config@*:
    peerDependencies:
      typescript: "*"
  apollo-server-micro@*:
    peerDependencies:
      graphql: "*"
  next@*:
    peerDependencies:
      "@babel/core": "*"
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  styled-jsx@*:
    peerDependencies:
      "@babel/core": "*"
  next-auth@*:
    peerDependencies:
      "@prisma/client": "*"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
