import { chakra } from "@chakra-ui/react";
import { FC, SVGAttributes } from "react";
import ShopLaptopSvg from "./shop-laptop.svg";

export { default as BoxCancel } from "./box-cancel";
export { default as BoxLoadDown } from "./box-load-down";
export { default as BoxLoadUp } from "./box-load-up";
export { default as BoxLock } from "./box-lock";
export { default as BoxOk } from "./box-ok";
export { default as BoxSearch } from "./box-search";
export { default as BoxSettings } from "./box-settings";
export { default as BoxShield } from "./box-shield";
export { default as BrowserAlert } from "./browser-alert";
export { default as BrowserBug } from "./browser-bug";
export { default as BrowserCancel } from "./browser-cancel";
export { default as BrowserKey } from "./browser-key";
export { default as BrowserLightbulb } from "./browser-lightbulb";
export { default as BrowserLink } from "./browser-link";
export { default as BrowserLoadDown } from "./browser-load-down";
export { default as BrowserLoadUp } from "./browser-load-up";
export { default as BrowserLock } from "./browser-lock";
export { default as BrowserSettings } from "./browser-settings";
export { default as BrowserShieldCancel } from "./browser-shield-cancel";
export { default as BrowserShieldOk } from "./browser-shield-ok";
export { default as BrowserTimeout } from "./browser-timeout";
export { default as BrowserTools } from "./browser-tools";
export { default as coffee } from "./coffee";
export { default as connection } from "./connection";
export { default as ConnectionOff } from "./connection-off";
export { default as CreditCard } from "./credit-card";
export { default as CreditCardLock } from "./credit-card-lock";
export { default as document } from "./document";
export { default as error } from "./error";
export { default as Error404 } from "./error-404";
export { default as folder } from "./folder";
export { default as gift } from "./gift";
export { default as image } from "./image";
export { default as map } from "./map";
export { default as MapGps } from "./map-gps";
export { default as message } from "./message";
export { default as NoWorkspaces } from "./no-workspace";
export { default as OfficeMan } from "./office-man";
export { default as OfficeWoman } from "./office-woman";
export { default as robot } from "./robot";
export { default as rocket } from "./rocket";
export { default as search } from "./search";
export { default as SearchGlobe } from "./search-globe";
export { default as SearchKey } from "./search-key";
export { default as SearchQuestion } from "./search-question";
export { default as team } from "./team";

export const ShopLaptop = chakra<FC<SVGAttributes<SVGElement>>>(ShopLaptopSvg);
